# Generated by Django 5.0.4 on 2024-05-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyg_1', '0002_post_comment_profil_takip_takipci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='eklenme_tarihi',
        ),
        migrations.AddField(
            model_name='post',
            name='baslik',
            field=models.TextField(default=42),
            preserve_default=False,
        ),
    ]
