# Generated by Django 5.0.4 on 2024-05-05 15:11

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uyg_1", "0003_rename_date_post_eklenme_tarihi_post_baslik"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="im")),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default_title", max_length=150)),
                (
                    "keywords",
                    models.CharField(default="default_keywords", max_length=255),
                ),
                ("descriptions", models.CharField(default="", max_length=255)),
                ("email", models.CharField(blank=True, max_length=15)),
                ("smtpserver", models.CharField(max_length=20)),
                ("smtpemail", models.CharField(max_length=20)),
                ("smtppassword", models.CharField(max_length=10)),
                ("smtpport", models.CharField(blank=True, max_length=5)),
                ("icon", models.ImageField(blank=True, upload_to="images")),
                ("facebook", models.CharField(max_length=50)),
                ("ins", models.CharField(max_length=50)),
                ("twit", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="Post-İmage/"),
        ),
        migrations.AddField(
            model_name="category",
            name="keywords",
            field=models.CharField(default="default_keywords", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="uyg_1.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="default-slug"),
        ),
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("True", "Evet"), ("False", "Hayır")],
                default="default_status",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(default="default_title", max_length=30),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(default="default_title", max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="baslik",
            field=models.TextField(default="default_title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="eklenme_tarihi",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ürün",
            name="isim",
            field=models.CharField(default="default_title", max_length=100),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default_title", max_length=30)),
                (
                    "keywords",
                    models.CharField(default="default_keywords", max_length=255),
                ),
                ("description", models.CharField(default="", max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="Post-İmage/")),
                ("price", models.FloatField()),
                ("amount", models.IntegerField()),
                ("detail", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "status",
                    models.CharField(
                        choices=[(True, "Evet"), (False, "Hayır")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="uyg_1.category"
                    ),
                ),
            ],
        ),
    ]
