# Generated by Django 5.0.4 on 2024-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uyg_1", "0004_foo_images_setting_remove_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settingg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default_title", max_length=150)),
                (
                    "keywords",
                    models.CharField(default="default_keywords", max_length=255),
                ),
                ("descriptions", models.CharField(default="", max_length=255)),
                ("email", models.CharField(blank=True, max_length=15)),
                ("smtpserver", models.CharField(blank=True, max_length=20)),
                ("smtpemail", models.CharField(blank=True, max_length=20)),
                ("smtppassword", models.CharField(blank=True, max_length=10)),
                ("smtpport", models.CharField(blank=True, max_length=5)),
                ("icon", models.ImageField(blank=True, upload_to="images")),
                ("facebook", models.CharField(blank=True, max_length=50)),
                ("ins", models.CharField(blank=True, max_length=50)),
                ("twit", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
