# Generated by Django 5.0.4 on 2024-05-05 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uyg_1", "0005_settingg_delete_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
    ]
