# Generated by Django 5.0.4 on 2024-05-06 08:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uyg_1", "0006_remove_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingg",
            name="aboutus",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name="settingg",
            name="contact",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name="settingg",
            name="references",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
